name: Build Minecraft Server Image

concurrency:
  group: build-minecraft-image-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  # We are going to build an image and push it to ghcr.io (GitHub Container Registry)
  build-final-image:
    name: Build Final Image
    runs-on: ubuntu-latest

    permissions:
      packages: write # Needed to push docker image to ghcr.io
      contents: read # Needed to read code in repository

    steps:
      # Docker buildx is useful for caching images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - id: set-var
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v4
        with:
          push: true
          # Add tags but lowercase the branch name
          tags: |
            ghcr.io/${{ steps.set-var.outputs.lowercase }}:latest
            ghcr.io/${{ steps.set-var.outputs.lowercase }}:${{ github.head_ref }}
          cache-from: type=gha # This will use the cached image from the last time we built it (Caching requires buildx done above)
          cache-to: type=gha,mode=max # This will cache the image for the next time we build it (max means it will cache all layers)
          labels: |
            org.opencontainers.image.title=latest
            org.opencontainers.image.description=The most recent image built from the main branch
            org.opencontainers.image.source=ghcr.io/${{ steps.set-var.outputs.lowercase }}
